### ISSUE TITLE
Puppet 8 mcorpc undefined method error

### ISSUE THREAD

**Issue by dom0317** [choria-io/general#43]
With puppet-agent 8.2.0 which contains ruby 3.2.2 and choria-mcorpc-support-2.26.2.gem installed
get "undefined method `thread'" error when running a command line mco rpc <agent> <action> 

The error in choria-mcorpc.log is:

E, [2023-10-26T12:42:08.405055 #354559] ERROR -- : agent.rb:102:in `rescue in handlemsg' lv#lvs failed: NoMethodError: undefined method `thread' for #<Process::Status: pid 354562 exit 0>
E, [2023-10-26T12:42:08.405221 #354559] ERROR -- : agent.rb:103:in `rescue in handlemsg' /opt/puppetlabs/puppet/lib/ruby/gems/3.2.0/gems/choria-mcorpc-support-2.26.2/lib/mcollective/shell.rb:125:in `runcommand'
        /opt/puppetlabs/puppet/lib/ruby/gems/3.2.0/gems/choria-mcorpc-support-2.26.2/lib/mcollective/rpc/agent.rb:215:in `run'
        /opt/puppetlabs/mcollective/plugins/mcollective/agent/lv.rb:28:in `block in <class:Lv>'
        /opt/puppetlabs/puppet/lib/ruby/gems/3.2.0/gems/choria-mcorpc-support-2.26.2/lib/mcollective/rpc/agent.rb:85:in `handlemsg'
        /usr/bin/choria_mcollective_agent_compat.rb:99:in `block in dispatch'
        /opt/puppetlabs/puppet/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
        /opt/puppetlabs/puppet/lib/ruby/3.2.0/timeout.rb:36:in `block in catch'
        /opt/puppetlabs/puppet/lib/ruby/3.2.0/timeout.rb:36:in `catch'
        /opt/puppetlabs/puppet/lib/ruby/3.2.0/timeout.rb:36:in `catch'
        /opt/puppetlabs/puppet/lib/ruby/3.2.0/timeout.rb:198:in `timeout'
        /usr/bin/choria_mcollective_agent_compat.rb:94:in `dispatch'
        /usr/bin/choria_mcollective_agent_compat.rb:117:in `<main>'

**Comment by ripienaar** [comment]
That's from here https://github.com/choria-io/mcorpc-ruby-support/blob/70c6dc0a3144a57423c06f2efc008d1be4d5c75c/lib/mcollective/shell.rb#L124 we can just remove that line really, its not needed in the current execution model.

Want to send a PR?
