### ISSUE TITLE
Support for special certname

### ISSUE THREAD

**Issue by teluq-pbrideau** [choria-io/general#54]
Not sure where to ask about my problem, so here it is.

My linux client is connected to a Microsoft Active Directory linked with FreeIPA. Therefore, my user is defined as `testpbrideau@example.net` instead of the usual `testpbrideau`.

My setup work perfectly with a regular account, but I can’t find how to enroll an Active Directory user.

### Builtin puppet enroll
The regular enroll throw an error:
```
:~$ whoami
testpbrideau@example.net

:~$ id
uid=XXX(testpbrideau@example.net) gid=XXX(testpbrideau@example.net) [...]

:~$ choria enroll
Enrolling with the Security System using certname testpbrideau@example.net.mcollective
choria: error: Could not enroll: could not submit csr: could not send CSR to https://puppet.linux.example.net:8140: 404 Not Found: Not Found
```

I tried manually generate the certificate on the puppetmaster, and it throws the same error.  I think puppet does not like the `@` char.
```
:~# puppetserver ca generate --certname 'testpbrideau@example.net.mcollective'      
Successfully saved private key for testpbrideau@example.net.mcollective to /etc/puppetlabs/puppet/ssl/private_keys/testpbride
au@example.net.mcollective.pem                                                                                               
Successfully saved public key for testpbrideau@example.net.mcollective to /etc/puppetlabs/puppet/ssl/public_keys/testpbrideau
@example.net.mcollective.pem                                                                                                 
Error:                                                                                                                         
    When attempting to submit certificate request for 'testpbrideau@example.net.mcollective', received:                      
      code: 404                                                                                                                
      body: Not Found
```

The same error is given by both puppetserver 7.17.3 and 8.7.0

### Custom certname
I’ve tried registering with a custom `--certname`, that works correctly:
```
:~$ choria enroll --certname testpbrideau.mcollective
Enrolling with the Security System using certname testpbrideau.mcollective
Certificate fingerprint: xxxxx

Attempting to download certificate for testpbrideau.mcollective, try 1
Attempting to download certificate for testpbrideau.mcollective, try 2

:~$ openssl x509 -in /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/certs/testpbrideau.mcollective.pem -noout -subject -issuer
subject=CN=testpbrideau.mcollective
issuer=CN=Puppet CA: puppet.linux.example.net

```

But I can’t find the way to use this certificate.  I’ve defined the certificate, in `~/.choriarc`
```
:~$ cat .choriarc
plugin.security.provider = file
plugin.security.file.certificate = ~/.puppetlabs/etc/puppet/ssl/certs/testpbrideau.mcollective.pem
plugin.security.file.key = ~/.puppetlabs/etc/puppet/ssl/private_keys/testpbrideau.mcollective.pem
plugin.security.file.ca = ~/.puppetlabs/etc/puppet/ssl/certs/ca.pem
```

But I still have error, choria seems to still try to find the certname `testpbrideau@example.net.mcollective`, that is the wrong CN.
```
:~$ mco choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.24.1
         Choria Version: 0.19.0
     Client Config File: /home/example.net/testpbrideau/.choriarc
     Active Config File: /home/example.net/testpbrideau/.choriarc
      Plugin Config Dir: /home/example.net/testpbrideau/plugin.d
      Using SRV Records: true
              Federated: false
             SRV Domain: linux.example.net
               NATS NGS: false
     Middleware Servers: choria.linux.example.net:4222

Puppet related:

       Puppet Server: puppet.linux.example.net:8140
     PuppetCA Server: puppet.linux.example.net:8140
     PuppetDB Server: puppetdb.linux.example.net:8081
     Discovery Proxy: not using a proxy
      Facter Command: /opt/puppetlabs/bin/facter
       Facter Domain: linux.example.net

Security setup:

     Valid SSL Setup: no try running 'choria enroll'
   Security Provider: file
            Certname: testpbrideau@example.net.mcollective
       SSL Directory: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl (found)
  Client Public Cert: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/certs/testpbrideau.mcollective.pem (found)
  Client Private Key: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/private_keys/testpbrideau.mcollective.pem (found)
             CA Path: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/certs/ca.pem (found)
            CSR Path:  (absent)

The choria application failed to run, use -v for full error backtrace details: Could not parse certificate with subject /CN=testpbrideau.mcollective as it has no CN part, or name testpbrideau@example.net.mcollective invalid
```

I don’t know if it helps, but the backtrace details are:
```
Could not parse certificate with subject /CN=testpbrideau.mcollective as it has no CN part, or name testpbrideau@example.net.mcollective invalid (RuntimeError)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.26.4/lib/mcollective/util/choria.rb:407:in `valid_certificate?'  <----
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.26.4/lib/mcollective/application/choria.rb:129:in `show_config_command'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.26.4/lib/mcollective/application/choria.rb:35:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.26.4/lib/mcollective/application.rb:313:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.26.4/lib/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.7.0/gems/choria-mcorpc-support-2.26.4/bin/mco:33:in `<top (required)>'
	from /usr/bin/mco:23:in `load'
	from /usr/bin/mco:23:in `<main>'
```

I cannot find documentation about this…   I’ve tried blindly to define a value `plugin.security.file.certname` and it does not work. Is there a way to configure the `certname` part in `~/.choriarc`?

**Comment by ripienaar** [comment]
Not sure why your enroll and such is failing, must be something to do with the Puppet CA routes maybe, no idea.

Can you show `choria tool config` please? Could be something ruby specific so just want to double check that output

**Comment by ripienaar** [comment]
Perhaps they dont allow @ in the route paths?

Can you show this config file, the one in /etc and if you have any choria.conf anywhere? Though tbf the `choria tool config` would have shown that clearly if you had so I am just trying to figure it out.

Could also be that the `.choriarc` is too minimal and its doing some defaults, can you try put all the stuff from `/etc/choria/client.conf` into your `.choriarc` and also maybe see what's in your /etc/choria/plugin.d if there's something there.

**Comment by teluq-pbrideau** [comment]
> Perhaps they dont allow @ in the route paths?

If you mean puppet, that’s also what I think, that is why I generated a certificate that does not use the @example.net part.
```
:~$ choria enroll --certname testpbrideau.mcollective
```

But the Certname and Caller ID defined in `choria tool config` is still related to @example.net.mcollective

```
             Caller ID: choria=testpbrideau@example.net.mcollective
              Certname: testpbrideau@example.net.mcollective
```

The error is pretty clear to me
```
Could not parse certificate with subject /CN=testpbrideau.mcollective as it has no CN part, or name testpbrideau@example.net.mcollective invalid
 ```
So I think I must define this «Caller ID» and «Certname» somewhere

> Can you show this config file, the one in /etc 



What do you mean by «this config file» ?  Do you mean my `client.conf`?

```
:~$ cat /etc/choria/client.conf 
collectives = mcollective
connection_timeout = 3
connector = nats
identity = pbrideau.linux.example.net
libdir = /opt/puppetlabs/mcollective/plugins
logger_type = console
loglevel = warn
main_collective = mcollective
securityprovider = choria
```
> and if you have any choria.conf anywhere? 

no file name `choria.conf` exist on my system
```
:~$ find / -name choria.conf 2>/dev/null
```

> 
> Could also be that the `.choriarc` is too minimal and its doing some defaults, can you try put all the stuff from `/etc/choria/client.conf` into your `.choriarc` 

I’ve tried pasting the entire `/etc/choria/client.conf` in my `.choriarc` and still no luck.

> and also maybe see what's in your /etc/choria/plugin.d if there's something there.

Only a file `actionpolicy.cfg`:
```
:~$ cat /etc/choria/plugin.d/actionpolicy.cfg 
allow_unconfigured = 0
enable_default = 0
```

**Comment by ripienaar** [comment]
Then maybe its a bug in how `.choriarc` is handled by Choria, for a test can you update /etc/choria/client.conf with the settings just to see if it parses better?

**Comment by teluq-pbrideau** [comment]
Well, there is progression!  The `mco choria show_config` does not crash anymore

```
MCOLLECTIVE_CERTNAME=testpbrideau.mcollective mco choria show_config
Active Choria configuration:

The active configuration used in Choria comes from using Puppet AIO defaults, querying SRV
records and reading configuration files.  The below information shows the completely resolved
configuration that will be used when running MCollective commands

MCollective related:

    MCollective Version: 2.24.1
         Choria Version: 0.19.0
     Client Config File: /home/example.net/testpbrideau/.choriarc
     Active Config File: /home/example.net/testpbrideau/.choriarc
      Plugin Config Dir: /home/example.net/testpbrideau/plugin.d
      Using SRV Records: true
              Federated: false
             SRV Domain: linux.example.net
               NATS NGS: false
     Middleware Servers: choria.linux.example.net:4222

Puppet related:

       Puppet Server: puppet.linux.example.net:8140
     PuppetCA Server: puppet.linux.example.net:8140
     PuppetDB Server: puppetdb.linux.example.net:8081
     Discovery Proxy: not using a proxy
      Facter Command: /opt/puppetlabs/bin/facter
       Facter Domain: linux.example.net

Security setup:

     Valid SSL Setup: yes
   Security Provider: file
            Certname: testpbrideau.mcollective
       SSL Directory: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl (found)
  Client Public Cert: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/certs/testpbrideau.mcollective.pem (found)
  Client Private Key: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/private_keys/testpbrideau.mcollective.pem (found)
             CA Path: /home/example.net/testpbrideau/.puppetlabs/etc/puppet/ssl/certs/ca.pem (found)
            CSR Path:  (absent)
      Public Cert CN: testpbrideau.mcollective (match)

Active Choria configuration settings as found in configuration files:

  No custom Choria settings found in your configuration files

```

Now, if I try `mco ping`, I get an error: `No plugin connector_plugin defined`

```
:~$ MCOLLECTIVE_CERTNAME=testpbrideau.mcollective mco ping

The ping application failed to run, use -v for full error backtrace details: No plugin connector_plugin defined
```

Could it be related to the «Plugin Config Dir». I tried creating a symlink without success.  It could be better if I could configure it in my `.choriarc`, but I’m not sure it is the way to go

```
:~$ MCOLLECTIVE_CERTNAME=testpbrideau.mcollective mco choria show_config | grep 'Plugin Config Dir'
      Plugin Config Dir: /home/example.net/testpbrideau/plugin.d

:~$ ln -s /etc/choria/plugin.d/ .

:~$ ls -l /home/example.net/testpbrideau/plugin.d
lrwxrwxrwx 1 testpbrideau@example.net testpbrideau@example.net 21 Nov 27 10:52 /home/example.net/testpbrideau/plugin.d -> /etc/choria/plugin.d/

:~$ MCOLLECTIVE_CERTNAME=testpbrideau.mcollective mco ping

The ping application failed to run, use -v for full error backtrace details: No plugin connector_plugin defined

```

**Comment by ripienaar** [comment]
Your choriarc replace the one in /etc needs all the settings

**Comment by teluq-pbrideau** [comment]
I’ve pasted my entire `/etc/choria/client.conf` to my `.choriarc`, as so:
```
:~$ cat .choriarc 
collectives = mcollective
connection_timeout = 3
connector = nats
identity = pbrideau.linux.example.net
libdir = /opt/puppetlabs/mcollective/plugins
logger_type = console
loglevel = warn
main_collective = mcollective
securityprovider = choria

plugin.security.provider = file
plugin.security.file.certificate = ~/.puppetlabs/etc/puppet/ssl/certs/testpbrideau.mcollective.pem
plugin.security.file.key = ~/.puppetlabs/etc/puppet/ssl/private_keys/testpbrideau.mcollective.pem
plugin.security.file.ca = ~/.puppetlabs/etc/puppet/ssl/certs/ca.pem
```

Now I have another error, `public key mismatch`, but it is the same error as if I do not set the `MCOLLECTIVE_CERTNAME` env variable, as if the variable is not use by `mco`
```
:~$ MCOLLECTIVE_CERTNAME=testpbrideau.mcollective mco ping

The ping application failed to run, use -v for full error backtrace details: public key mismatch

:~$ mco ping

The ping application failed to run, use -v for full error backtrace details: public key mismatch
```

Should I also add the content of `/etc/choria/choria-shim.cfg` to my `.choriarc` ? I tried without success.
Should I keep the symlink in `~/plugin.d`?

**Comment by ripienaar** [comment]
You can create ~/choria.conf which will merge with /etc/choria/client.conf (you can put it in any directory and it searches up till it finds it) this is much easier.

For the key mismatch, that suggests your tls key and cert and pub key aren't from the same - double check all that

**Comment by teluq-pbrideau** [comment]
> For the key mismatch, that suggests your tls key and cert and pub key aren't from the same - double check all that

Oh, yes, you were right, the problem was with the puppet certs I created and destroyed multiple times while debugging.
I destroyed and recreated my certificate with the puppet CA, and now everything works perfectly!

### In the end
Thanks for your time, the problem was really about defining the environment variable `MCOLLECTIVE_CERTNAME` at first.  no need to mess with the `.choriarc`.  Once the env variable is set, it all works out of the box.  Is it documented somewhere I missed?

I’ll create a config in `/etc/profile.d/` to define this env variable if the user have an @ in their username


### For reference
Here is what I did in the end, for anyone wanting to only see the end results:

```
:~$ echo 'export MCOLLECTIVE_CERTNAME=testpbrideau.mcollective' >> ~/.bashrc
:~$ source ~/.bashrc
:~$ choria enroll
:~$ mco ping
```

**Comment by ripienaar** [comment]
I doubt its in the docs as we really favour the happy path of puppet-agent on standard machines, changing these kinds of things works and solve the problem but I dont want to encourage huge variance in how people deploy it

**Comment by teluq-pbrideau** [comment]
You’re probably right.  Also, once I logout and login again, something broke, so I’m not sure about my «For reference» section.  But I’ll be all right to debug on my own, thanks again.
